# Generated by Django 2.2.7 on 2019-11-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='squirrel',
            fields=[
                ('x', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=1007)),
                ('y', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=1006)),
                ('unique_squirrel_id', models.CharField(blank=True, default=None, max_length=14, primary_key=True, serialize=False)),
            ],
        ),
    ]
