# Generated by Django 2.2.7 on 2019-11-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='unique_squirrel_id',
            field=models.CharField(blank=True, max_length=14, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='x',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=1007),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='y',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=1006),
        ),
    ]
