# Generated by Django 2.2.7 on 2019-11-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0004_auto_20191122_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='above_ground_sighter_measurement',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
    ]
