# Generated by Django 2.2.7 on 2019-11-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0005_auto_20191122_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='approaches',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='borough_boundaries',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='city_coucil_districts',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='community_districts',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='indifferent',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='lat_long',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='other_interactions',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='police_precincts',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='runs_from',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='zip_codes',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
