# Generated by Django 2.2.7 on 2019-11-26 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0007_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='entry',
        ),
    ]
